[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "PORT=${PORT} node .next/standalone/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 10
timeout = 30000  # 30 seconds timeout

[env]
NODE_ENV = "production"
NEXTAUTH_URL = "https://pleadex.com"
NEXTAUTH_SECRET = "CM/iQuRfCvo16PWyhBw5iarHfGfs0ki9MNbVuYA+FW8="
MONGODB_URI = "mongodb+srv://bcolombana:0openSesame123!@#@pleadex-cluster.f5dcgdt.mongodb.net/pleadex?retryWrites=true&w=majority&appName=pleadex-cluster"
DATABASE_URL = "mongodb+srv://bcolombana:0openSesame123!@#@pleadex-cluster.f5dcgdt.mongodb.net/pleadex?retryWrites=true&w=majority&appName=pleadex-cluster"
NEXT_PUBLIC_APP_URL = "https://pleadex.com"

[build.cache]
paths = [
  ".next/cache",
  "node_modules/.cache"
] 