[build]
builder = "nixpacks"
buildCommand = "npm install && prisma generate && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production" 