[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "PORT=${PORT} node .next/standalone/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 10
timeout = 30000  # 30 seconds timeout

[env]
NODE_ENV = "production"
NEXTAUTH_URL = "https://pleadex.com"
NEXTAUTH_SECRET = "CM/iQuRfCvo16PWyhBw5iarHfGfs0ki9MNbVuYA+FW8="
# MongoDB credentials should be set in Railway's environment variables, not here
NEXT_PUBLIC_APP_URL = "https://pleadex.com"

[build.cache]
paths = [
  ".next/cache",
  "node_modules/.cache"
] 